# Generated by Django 4.2.16 on 2026-03-12 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(help_text='Unique work order identifier', max_length=50, unique=True)),
                ('product_code', models.CharField(help_text='Product code from warehouse', max_length=50)),
                ('product_name', models.CharField(blank=True, help_text='Denormalized product name for performance', max_length=200)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g., Operator, Supervisor', max_length=100)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workorder')),
            ],
            options={
                'unique_together': {('work_order', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='work_orders', through='production.WorkOrderAssignment', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='production.productionline'),
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('output_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scrap_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('downtime_minutes', models.PositiveIntegerField(default=0, help_text='Downtime in minutes')),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to='hr.employee')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.workorder')),
            ],
            options={
                'verbose_name': 'Production Log',
                'verbose_name_plural': 'Production Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
