# Generated by Django 4.2.16 on 2026-03-12 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='hr.department')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['title'],
                'unique_together': {('title', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='NIK Karyawan', max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('no_ktp', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('no_kk', models.CharField(blank=True, max_length=30)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('kelurahan', models.CharField(blank=True, max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100)),
                ('kabupaten_kota', models.CharField(blank=True, max_length=100)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('status_kawin', models.CharField(blank=True, choices=[('bk', 'Belum Kawin'), ('kawin', 'Kawin'), ('cerai', 'Cerai'), ('cerai_mati', 'Cerai Mati')], max_length=20, null=True)),
                ('tanggungan', models.IntegerField(blank=True, default=0, null=True)),
                ('agama', models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu')], max_length=20, null=True)),
                ('tinggi_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gol_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=50)),
                ('tgl_rekrut', models.DateField(blank=True, null=True)),
                ('status_karyawan', models.CharField(choices=[('tetap', 'Tetap'), ('kontrak', 'Kontrak'), ('probation', 'Probation'), ('harian', 'Harian')], default='kontrak', max_length=20)),
                ('tgl_kartetap', models.DateField(blank=True, null=True)),
                ('posisi_karyawan', models.CharField(blank=True, max_length=100)),
                ('no_kartu_kpk', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('dept', models.CharField(blank=True, max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('kontrak_ke', models.IntegerField(blank=True, default=0, null=True)),
                ('kontrak_berakhir', models.DateField(blank=True, null=True)),
                ('kode_gaji', models.CharField(blank=True, max_length=20)),
                ('no_rek_bank', models.CharField(blank=True, max_length=50)),
                ('kode_bank', models.CharField(blank=True, max_length=10)),
                ('nama_bank', models.CharField(blank=True, max_length=50)),
                ('status_ptkp', models.CharField(blank=True, choices=[('tk0', 'TK0'), ('tk1', 'TK1'), ('tk2', 'TK2'), ('tk3', 'TK3'), ('k0', 'K0'), ('k1', 'K1'), ('k2', 'K2'), ('k3', 'K3')], max_length=10, null=True)),
                ('no_npwp', models.CharField(blank=True, max_length=30)),
                ('bpjs_tk', models.CharField(blank=True, max_length=50)),
                ('bpjs_tk_ditanggung', models.CharField(blank=True, max_length=100)),
                ('bpjs_tk_no', models.CharField(blank=True, max_length=30)),
                ('bpjs_kes', models.CharField(blank=True, max_length=50)),
                ('bpjs_kes_ditanggung', models.CharField(blank=True, max_length=100)),
                ('bpjs_kes_no', models.CharField(blank=True, max_length=30)),
                ('status_pajak', models.CharField(blank=True, choices=[('npwp', 'Memiliki NPWP'), ('non_npwp', 'Tidak Memiliki NPWP')], max_length=20, null=True)),
                ('faskes', models.CharField(blank=True, max_length=100)),
                ('placement', models.CharField(blank=True, max_length=100)),
                ('tgl_out', models.DateField(blank=True, null=True)),
                ('status_kerja', models.CharField(blank=True, max_length=20)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('retired', 'Retired')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('hr', 'HR Staff'), ('production', 'Production Staff'), ('warehouse', 'Warehouse Staff'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator')], default='operator', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.position')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
    ]
