# Generated by Django 4.2.16 on 2026-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status_karyawan',
            field=models.CharField(choices=[('tetap', 'Tetap'), ('kontrak', 'Kontrak'), ('os', 'OS'), ('probation', 'Probation'), ('harian', 'Harian')], default='kontrak', max_length=20),
        ),
    ]
